"""Generated by dezzy Python backend"""
from dataclasses import dataclass
from typing import List
import struct

@dataclass
class Chunk:
    length: int  # Length of the data field
    chunk_type: List[int]  # 4-byte chunk type identifier (e.g., IHDR, IDAT)
    data: List[int]  # Variable-length chunk data
    crc: int  # CRC32 checksum

    @staticmethod
    def read(buffer: bytes, offset: int = 0) -> tuple['Chunk', int]:
        """Read Chunk from bytes. Returns (instance, bytes_read)"""
        pos = offset
        length = struct.unpack_from('>I', buffer, pos)[0]
        pos += struct.calcsize('>I')
        chunk_type = []
        for _ in range(4):
            val = struct.unpack_from('>B', buffer, pos)[0]
            pos += struct.calcsize('>B')
            chunk_type.append(val)
        data = []
        for _ in range(length):
            val = struct.unpack_from('>B', buffer, pos)[0]
            pos += struct.calcsize('>B')
            data.append(val)
        crc = struct.unpack_from('>I', buffer, pos)[0]
        pos += struct.calcsize('>I')
        return Chunk(length, chunk_type, data, crc), pos - offset

    def write(self) -> bytes:
        """Write Chunk to bytes"""
        result = bytearray()
        result.extend(struct.pack('>I', self.length))
        for item in self.chunk_type:
            result.extend(struct.pack('>B', item))
        for item in self.data:
            result.extend(struct.pack('>B', item))
        result.extend(struct.pack('>I', self.crc))
        return bytes(result)


