"""Generated by dezzy Python backend"""
from dataclasses import dataclass
from enum import IntEnum
from typing import List, Optional
import struct

@dataclass
class VersionedMessage:
    version: int
    v1_data: Optional[int] = None
    v2_data: Optional[int] = None
    flags: int
    extra_info: Optional[int] = None

    @staticmethod
    def read(buffer: bytes, offset: int = 0) -> tuple['VersionedMessage', int]:
        """Read VersionedMessage from bytes. Returns (instance, bytes_read)"""
        pos = offset
        version = struct.unpack_from('B', buffer, pos)[0]
        pos += 1
        if (version == 1):
            v1_data = struct.unpack_from('<I', buffer, pos)[0]
            pos += 4
        if (version == 2):
            v2_data = struct.unpack_from('<Q', buffer, pos)[0]
            pos += 8
        flags = struct.unpack_from('B', buffer, pos)[0]
        pos += 1
        if (flags > 0):
            extra_info = struct.unpack_from('<H', buffer, pos)[0]
            pos += 2
        return VersionedMessage(version, v1_data, v2_data, flags, extra_info), pos - offset

    def write(self) -> bytes:
        """Write VersionedMessage to bytes"""
        result = bytearray()
        result.extend(struct.pack('B', self.version))
        if (self.version == 1):
            result.extend(struct.pack('<I', self.v1_data))
        if (self.version == 2):
            result.extend(struct.pack('<Q', self.v2_data))
        result.extend(struct.pack('B', self.flags))
        if (self.flags > 0):
            result.extend(struct.pack('<H', self.extra_info))
        return bytes(result)


