"""Generated by dezzy Python backend"""
from dataclasses import dataclass
from enum import IntEnum
from typing import List
import struct

@dataclass
class Header:
    magic: List[int]  # Magic number signature
    version: int  # Version number (must be >= 1)
    width: int  # Image width (must be > 0)
    height: int  # Image height (must be > 0)
    flags: int  # Flags field (must be in range 0-7)

    @staticmethod
    def read(buffer: bytes, offset: int = 0) -> tuple['Header', int]:
        """Read Header from bytes. Returns (instance, bytes_read)"""
        pos = offset
        magic = []
        for _ in range(4):
            val = struct.unpack_from('B', buffer, pos)[0]
            pos += 1
            magic.append(val)
        expected = [137, 80, 78, 71]
        if list(magic) != expected:
            raise ValueError("Field 'magic' does not match expected value")
        version = struct.unpack_from('>H', buffer, pos)[0]
        pos += 2
        if version < 1:
            raise ValueError("Field 'version' must be >= 1, got {}".format(version))
        width = struct.unpack_from('>I', buffer, pos)[0]
        pos += 4
        if width <= 0:
            raise ValueError("Field 'width' must be greater than 0, got {}".format(width))
        height = struct.unpack_from('>I', buffer, pos)[0]
        pos += 4
        if height <= 0:
            raise ValueError("Field 'height' must be greater than 0, got {}".format(height))
        flags = struct.unpack_from('B', buffer, pos)[0]
        pos += 1
        if flags < 0 or flags > 7:
            raise ValueError("Field 'flags' must be in range [0, 7], got {}".format(flags))
        return Header(magic, version, width, height, flags), pos - offset

    def write(self) -> bytes:
        """Write Header to bytes"""
        result = bytearray()
        for item in self.magic:
            result.extend(struct.pack('>B', item))
        result.extend(struct.pack('>H', self.version))
        result.extend(struct.pack('>I', self.width))
        result.extend(struct.pack('>I', self.height))
        result.extend(struct.pack('>B', self.flags))
        return bytes(result)


