"""Generated by dezzy Python backend"""
from dataclasses import dataclass
from enum import IntEnum
from typing import List
import struct

class Status(IntEnum):
    OK = 0
    ERROR = 1
    PENDING = 2


@dataclass
class Message:
    status: Status
    value: int

    @staticmethod
    def read(buffer: bytes, offset: int = 0) -> tuple['Message', int]:
        """Read Message from bytes. Returns (instance, bytes_read)"""
        pos = offset
        status = struct.unpack_from('B', buffer, pos)[0]
        pos += 1
        value = struct.unpack_from('>I', buffer, pos)[0]
        pos += 4
        return Message(status, value), pos - offset

    def write(self) -> bytes:
        """Write Message to bytes"""
        result = bytearray()
        result.extend(struct.pack('>B', self.status))
        result.extend(struct.pack('>I', self.value))
        return bytes(result)


